version: 2

workflows:
  version: 2
  build:
    jobs:
      - tests
      - quality
      - ikos

jobs:
  tests:
    docker:
      - image: charlesdaniels/openvcd:latest
    steps:
      - checkout
      - run: make RUN_TESTS=YES TEST_WITH_VALGRIND=YES CFLAGS="-std=c99 -Wall -Wextra -pedantic -Werror -O0 -g3" -C src

  quality:
    docker:
      - image: charlesdaniels/openvcd:latest
    steps:
      - checkout
      - run: lizard src/

  ikos:
    docker:
      - image: charlesdaniels/openvcd:latest
    steps:
      - checkout
      - run: sh -c 'yes | ikos-scan make -C src/ > ikos.log 2>&1' || true
      - run: mkdir -p /tmp/ikos_results
      - run: mv src/*.db /tmp/ikos_results
      - run: mv ikos.log /tmp/ikos_results
      - run: sh -c 'if grep "The program is definitely UNSAFE" < /tmp/ikos_results/ikos.log ; then exit 1 ; fi'
      - run: sh -c 'if grep "The program is potentially UNSAFE" < /tmp/ikos_results/ikos.log ; then exit 1 ; fi'
      - store_artifacts:
          path: /tmp/ikos_results


