version: 2

workflows:
  version: 2
  build:
    jobs:
      - tests
      - quality
      - ikos

jobs:
  tests:
    docker:
      - image: charlesdaniels/openvcd:latest
    steps:
      - checkout
      - run: make RUN_TESTS=YES TEST_WITH_VALGRIND=YES CFLAGS="-std=c99 -Wall -Wextra -pedantic -Werror -O0 -g3" -C src

  quality:
    docker:
      - image: charlesdaniels/openvcd:latest
    steps:
      - checkout
      - run: lizard src/

  ikos:
    docker:
      - image: charlesdaniels/openvcd:latest
    steps:
      - checkout
      - run: ikos-scan make
      - run: pwd
      - run: ls -lah
      - run: ls -lah src/


